In [1]:
import tensorflow as tf
print(tf.__version__)

2.2.0


In [13]:
import pandas as pd
import os
import numpy as np
import random
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

In [59]:
datadir="D:/learn/ML/Dancing ML/DanceDataset/train"
categories=["manipuri","bharatanatyam","odissi","kathakali","kathak","sattriya","kuchipudi","mohiniyattam"]
data=pd.read_csv("train.csv")
x=data["Image"]
y=data["target"]
path=os.path.join(datadir)
train_data=[]
for img,label in zip(x,y):
    img=load_img(os.path.join(path,img),target_size=(128,128))
    img_arr=np.array(img)
    train_data.append([img_arr,categories.index(label)])
    
random.shuffle(train_data)

In [74]:
X=[]
Y=[]
for features,labels in train_data:
    X.append(features)
    Y.append(labels)

X=np.array(X)
Y=np.array(Y)
X.shape
X=X/255.
Y = Y.reshape((len(Y), 1))
Y.shape


(364, 1)

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [78]:
oh=OneHotEncoder(sparse=False)
Y_enc=oh.fit_transform(Y)
print(Y_enc)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


D:\apps\Anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [63]:
from keras.models import Sequential,Model
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense,GlobalAveragePooling2D
from keras import applications

In [121]:
model=Sequential()
model.add(Conv2D(32,(3,3),input_shape=(128,128,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten()) 
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(8))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [122]:
model.fit(X,Y_enc,epochs=100,batch_size=32)

Epoch 1/100
12/12 [==============================] - 3s 225ms/step - loss: 2.1121 - accuracy: 0.1099
Epoch 2/100
12/12 [==============================] - 3s 223ms/step - loss: 2.0379 - accuracy: 0.1593
Epoch 3/100
12/12 [==============================] - 3s 238ms/step - loss: 1.9387 - accuracy: 0.2582
Epoch 4/100
12/12 [==============================] - 3s 290ms/step - loss: 1.7693 - accuracy: 0.3187
Epoch 5/100
12/12 [==============================] - 5s 416ms/step - loss: 1.5915 - accuracy: 0.4451
Epoch 6/100
12/12 [==============================] - 5s 407ms/step - loss: 1.3613 - accuracy: 0.5220
Epoch 7/100
12/12 [==============================] - 5s 415ms/step - loss: 1.1390 - accuracy: 0.5687
Epoch 8/100
12/12 [==============================] - 5s 403ms/step - loss: 1.0188 - accuracy: 0.6456
Epoch 9/100
12/12 [==============================] - 5s 416ms/step - loss: 0.8581 - accuracy: 0.7115
Epoch 10/100
12/12 [==============================] - 5s 431ms/step - loss: 0.7259 - accura

12/12 [==============================] - 5s 410ms/step - loss: 0.0686 - accuracy: 0.9753
Epoch 82/100
12/12 [==============================] - 5s 384ms/step - loss: 0.0709 - accuracy: 0.9753
Epoch 83/100
12/12 [==============================] - 5s 404ms/step - loss: 0.0785 - accuracy: 0.9698
Epoch 84/100
12/12 [==============================] - 5s 393ms/step - loss: 0.1065 - accuracy: 0.9670
Epoch 85/100
12/12 [==============================] - 5s 402ms/step - loss: 0.0926 - accuracy: 0.9588
Epoch 86/100
12/12 [==============================] - 5s 399ms/step - loss: 0.1076 - accuracy: 0.9615
Epoch 87/100
12/12 [==============================] - 5s 394ms/step - loss: 0.0618 - accuracy: 0.9780
Epoch 88/100
12/12 [==============================] - 5s 393ms/step - loss: 0.0573 - accuracy: 0.9753
Epoch 89/100
12/12 [==============================] - 5s 406ms/step - loss: 0.0798 - accuracy: 0.9725
Epoch 90/100
12/12 [==============================] - 5s 393ms/step - loss: 0.0732 - accuracy: 

In [128]:
model.fit(X,Y_enc,epochs=100,batch_size=32)

Epoch 1/100
12/12 [==============================] - 5s 425ms/step - loss: 0.0651 - accuracy: 0.9725
Epoch 2/100
12/12 [==============================] - 5s 411ms/step - loss: 0.0671 - accuracy: 0.9808
Epoch 3/100
12/12 [==============================] - 5s 410ms/step - loss: 0.1176 - accuracy: 0.9533
Epoch 4/100
12/12 [==============================] - 5s 409ms/step - loss: 0.0650 - accuracy: 0.9725
Epoch 5/100
12/12 [==============================] - 5s 408ms/step - loss: 0.0780 - accuracy: 0.9863
Epoch 6/100
12/12 [==============================] - 5s 418ms/step - loss: 0.1225 - accuracy: 0.9588
Epoch 7/100
12/12 [==============================] - 5s 421ms/step - loss: 0.0944 - accuracy: 0.9588
Epoch 8/100
12/12 [==============================] - 5s 407ms/step - loss: 0.0501 - accuracy: 0.9863
Epoch 9/100
12/12 [==============================] - 5s 407ms/step - loss: 0.0746 - accuracy: 0.9698
Epoch 10/100
12/12 [==============================] - 5s 409ms/step - loss: 0.0551 - accura

12/12 [==============================] - 5s 404ms/step - loss: 0.0435 - accuracy: 0.9835
Epoch 82/100
12/12 [==============================] - 5s 399ms/step - loss: 0.0345 - accuracy: 0.9863
Epoch 83/100
12/12 [==============================] - 5s 402ms/step - loss: 0.0348 - accuracy: 0.9835
Epoch 84/100
12/12 [==============================] - 5s 406ms/step - loss: 0.0738 - accuracy: 0.9808
Epoch 85/100
12/12 [==============================] - 5s 390ms/step - loss: 0.0541 - accuracy: 0.9753
Epoch 86/100
12/12 [==============================] - 5s 389ms/step - loss: 0.0554 - accuracy: 0.9780
Epoch 87/100
12/12 [==============================] - 5s 385ms/step - loss: 0.0513 - accuracy: 0.9753
Epoch 88/100
12/12 [==============================] - 5s 391ms/step - loss: 0.0698 - accuracy: 0.9698
Epoch 89/100
12/12 [==============================] - 5s 401ms/step - loss: 0.0508 - accuracy: 0.9780
Epoch 90/100
12/12 [==============================] - 5s 421ms/step - loss: 0.0538 - accuracy: 

In [118]:
datadir="D:/learn/ML/Dancing ML/DanceDataset/test"
path=os.path.join(datadir)
test_data=pd.read_csv("test.csv")
test_data=test_data["Image"]
test_x=[]
for img in test_data:
    img=load_img(os.path.join(path,img),target_size=(128,128))
    img_arr=np.array(img)
    test_x.append(img_arr)
test_x=np.array(test_x)

In [129]:
predictions=model.predict(test_x)
print(predictions)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [130]:
pred=model.evaluate(X,Y_enc)
print(pred)

12/12 [==============================] - 1s 124ms/step - loss: 1.0423e-04 - accuracy: 1.0000
[0.00010423196363262832, 1.0]


In [131]:
results_labels=np.argmax(predictions,axis=1)
print(results_labels)

[6 5 7 2 3 6 6 5 6 2 7 1 5 5 5 1 2 1 7 2 2 3 3 7 7 3 7 1 2 1 3 2 0 2 7 6 2
 2 0 1 4 5 2 7 7 7 5 5 5 6 7 7 4 6 2 2 2 2 5 5 3 5 4 2 6 6 3 3 2 1 4 6 2 7
 4 3 7 5 3 1 7 6 7 6 6 6 4 3 0 7 7 4 4 6 3 4 6 7 5 6 6 7 4 2 1 6 2 6 7 2 6
 3 6 2 6 2 3 3 7 6 2 7 5 7 2 7 5 5 6 2 1 3 1 3 4 7 6 7 2 4 5 4 6 2 4 7 4 5
 0 7 5 5 3 4 2 5]


In [132]:
results=[]
for i in results_labels:
    results.append(categories[i])


In [127]:
df=pd.DataFrame(results)
df.to_csv("results.csv")